# This workflow will install Python dependencies, run tests and lint with a
# single version of Python
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Set up Python 3.10"
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

  lint:
    # TODO: DRY this with tests job
    name: "Lint"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Set up Python 3.10"
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -e .

      - name: Run lint
        run: |
          pre-commit run --all-files


  # A summary of all jobs and their result.
  # This is the only job that's required to pass (as set by branch protection
  # rules in repo settings) so that we don't have to update those rules when
  # a new job is added.
  check-all-jobs:
    if: always()
    needs:
      - tests
      - lint
    runs-on: ubuntu-latest
    steps:
      - name: Check status of all jobs.
        uses: re-actors/alls-green@v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
